# Lists, Dictionaries and Sets in Python

## Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [1]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [2]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


### Question 1
Adding to an existing list

Add 10 to list l1 given above

*Hint:  Use `append()`*

In [3]:
l1.append(10)
l1

['learning', 'Python', 'is fun?', True, 10]

### Question 2
Removing from an existing list

Remove 10 from l1

*Hint: use `remove()`*

In [4]:
l1.remove(10)
l1

['learning', 'Python', 'is fun?', True]

### Question 3
Join 2 lists l1 and l2

Hint: use **`+`** operator or **`extend()`**

In [5]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [6]:
l1+l2

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]

### Question 4
Number List

Find Range and Mean of l3.

`l3 = [2,4,6,8]`

Hint: use **`len()`, `sum()`, `min()`, `max()`** functions
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [7]:
l3=[2,4,6,8]

In [8]:
len(l3)

4

In [35]:
sum(l3)

53

In [37]:
max(l3)

9

### Question 5
Count the occurances of an element in a given list

Append the given sequence of numbers to l3 (given above)

0, 1, 3, 3, 5, 5, 7, 9

Count the occurences of 5 in l3.

Hint: use **`+`** operator to add multiple elements in the array and **`count()`** function to print the occurences

In [9]:
l3=l3+[0,1,3,3,5,5,7,9]

In [10]:
l3

[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

In [11]:
l3.count(5)

2

### Question 6
Sorting and Reversing a list

sort and print l3 in ascending and descending order sequentially (given above)

Hint: use **`sort()`** function

In [12]:
l3


[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

In [13]:
sorted(l3,reverse=1)


[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]

In [14]:
l3

[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

## Functions

**Example:**

**def** function_name(args)**:**

    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [15]:
def sum_3(x,y,z):
    return x+y+z

In [16]:
sum_3(12,13,14)

39

## Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

sum_3 = lambda x,y,z: x+y+z

In [17]:
sum_3 = lambda x,y,z: x+y+z

In [18]:
sum_3(12,13,14)

39

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns and operating on 2d matrices aren't readily available. So, we will use ***Numpy*** for such functions.



In [19]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [20]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Some functions on np.array()

In [21]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

Hint: You can also use **`np.identity()`** function

In [22]:
np.identity(5)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9, 8, 7, 6, 5, 4, 3, 2, 1 arranged in the same order

Use: **`np.matrix()`** function



In [38]:
#sample_matrix = np.array(([9,8,7],[6,5,4],[3,2,1]))
sample_matrix = np.matrix('9 8 7;6 5 4;3 2 1')

In [39]:
sample_matrix

matrix([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**

In [40]:
sample_matrix.transpose()

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### Question 4
Add (+) 1 to all the elements in the given matrix.

In [41]:
sample_matrix+1

matrix([[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.

nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [27]:
nd6 = [[  1,   4,   9, 121, 144, 169], [ 16 , 25,  36, 196, 225, 256], [ 49,  64,  81, 289, 324, 361]]


In [42]:
np.matrix(nd6)

matrix([[  1,   4,   9, 121, 144, 169],
        [ 16,  25,  36, 196, 225, 256],
        [ 49,  64,  81, 289, 324, 361]])

In [43]:
np.mean(nd6)

131.66666666666666

### Question 6

Find the dot product of two given matrices.

Hint: use **`np.dot()`**

In [44]:
#dot product of sample_matrix and nd6
np.dot(sample_matrix,nd6)

matrix([[ 480,  684,  936, 4680, 5364, 6096],
        [ 282,  405,  558, 2862, 3285, 3738],
        [  84,  126,  180, 1044, 1206, 1380]])

# Pandas

We have seen Numpy in the last section. It is good at performing math operations on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](https://pandas.pydata.org/pandas-docs/stable/)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [30]:
import numpy as np
import pandas as pd

In [31]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

Hint: use **`.Series`**

In [32]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [33]:
pd.Series(d1)

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


Hint: use **`np.dot()`**

In [34]:
np.dot(d1,series1)

TypeError: unsupported operand type(s) for *: 'dict' and 'int'

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [ ]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

### Question 3

Select second row in the above dataframe df1.



In [ ]:
df1.loc[1]

### Question 4

Select column c in second row of df1.

Hint: For using labels use **`df.loc[row, column]`**

For using numeric indexed use **`df.iloc[]`**

For using mixture of numeric indexes and labels use **`df.ix[row, column]`**



In [ ]:
df1.loc[1,"c"]

## Using Dataframes on a dataset

### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors 


In [ ]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']
mtcars.index

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


Hint: use **`type()`** and **`df.shape`**

In [ ]:
mtcars.shape


In [ ]:
mtcars.dtypes

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

Hint: use **`.head()`** and **`.tail()`**

In [ ]:
mtcars.head()

### Question 7

Print all the column labels in the given dataset - mtcars.

Hint: use **`df.columns`**

In [ ]:
mtcars.tail()

In [ ]:
mtcars.head(2)

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

Hint: **`mtcars.ix[:, :]`** gives all rows and columns in the dataset

In [ ]:
mtcars.iloc[0:6,0:3]

### Question 7

Calculate the Inter-Quartile Range (IQR) for `mpg` in the given dataset.

Interquartile range (IQR) is another common measure of spread. IQR is the distance between the 3rd quartile and the 1st quartile.

**Hint:** IQR = Q3 - Q1

In [ ]:
Q1 = mtcars["mpg"].quantile(0.25)
Q3=mtcars["mpg"].quantile(0.75)
IQR = Q3 - Q1
IQR


### Question 8

Calculate the Variance, Standard Deviation and Median Absolute Deviation for `mpg`.

Variance and Standard Deviation are two other common measure of dispersion.

**Hint:** Use .var() and .std()

**Hint:** Median Absolute Deviation: alternative measure of spread based on the median. It is the median of the absolute value of the deviations from the median. 

In [ ]:
mtcars["mpg"].var()

In [ ]:
mtcars["mpg"].std()